### ISSUE TITLE
Wrong time when zooming in

### ISSUE THREAD

**Issue by kr3l** [timeglider/jquery_widget#11]
Hi, 

I have a few events plotted on the timeline, all of them in January 2010. All is good when the labels below the timeline show months (January, February). When I zoom in so that the labels switch to days, it suddenly says the events are in July (the labels say Jul 18,1 / Jul 19, 1 / ...)!

Hovering over the events still shows the correct date (in January). 

Karel

**Comment by timeglider** [comment]
I had a bug in TG_Date.getTimeUnitSerial() where I wasn't closing out a switch element with "break;" so it was outputting the next result. Just fixed this. Thanks for your patience.

**Comment by kr3l** [comment]
Thanks for the fix!

**Comment by Chris-Field** [comment]
I am having a similar problem (even though this is two years later).

I have a few dates set in January 2000 B.C.E.  However when I zoom in (and sometimes even when it's zoomed out; it's very finicky), it places the events in November -2004 (B.C.E.).

As with kr3l, when hovering over the events, the correct date of "January 2000 bce" still appears.
