### ISSUE TITLE
tool button images assume '/js' root

### ISSUE THREAD

**Issue by mlooney** [timeglider/jquery_widget#13]
the tool buttons at the bottom can't load their images unless timeglider is installed in exactly the right directory structure

**Comment by timeglider** [comment]
Ah! With other buttons I've been changing them to be purely CSS driven (sized divs with background images) so that the image directory can be relative to the CSS file. Would that make sense to you?

**Comment by mlooney** [comment]
that's what i was going to suggest, but didn't presume to know enough about how things are done in javascript land.

**Comment by mgarciabermejo** [comment]
You could fix this changing line 50 of timegrlider.timeline.widget.js

```
    icon_folder:'js/timeglider/icons/',
```

**Comment by timeglider** [comment]
Actually, @marcos128, we're talking about the buttons that go along with the filter, timeline list, and wrench buttons.  This is all CSS-driven now
