### ISSUE TITLE
Is `enddate` visible anywhere?

### ISSUE THREAD

**Issue by klauern** [timeglider/jquery_widget#16]
When I click on an event, I can see the start date and time, but I don't see anywhere that mentions the end.  I see that the end does dictate the length of the shadow behind the event, so there does appear to be _something_ showing an end time, but there's no place that specifically shows, "This event started on X,  and ended on Y".

Am I missing something?

**Comment by timeglider** [comment]
No ------- you're not missing anything: I need to put the
end date into the UI for events that are spans.  I'll do my
best to get to that in the next couple of weeks.

------ Michael

**Comment by timeglider** [comment]
This is all set: end dates are now visible in the hover and modal pop-up.
