### ISSUE TITLE
'focus_date' does not default to date of first event

### ISSUE THREAD

**Issue by jeremyboggs** [timeglider/jquery_widget#20]
The documentation indicates that the default for 'focus_date' is the date of the first event loaded on the timeline. However, when I omit 'focus_date' from the timeline options, the timeline breaks, even though there is an event with a valid 'startdate' fed to the timeline. If I explicitly set a 'focus_date' on the timeline options, the timeline loads correctly.

Curious whether this is a bug in the code, or if there is some other way of setting the 'focus_date' to the first event on the timeline.

**Comment by timeglider** [comment]
This is what one might call a "bug of omission" ----- as
I was writing the documentation, I was picturing what it
ought to be rather than what it was.  Will update the
actual code to reflect this (give me a few days).

Michael

**Comment by timeglider** [comment]
Okay. that took a while. Finally defaulting timeline with no provided focus date to first event's date.

**Comment by jeremyboggs** [comment]
Terrific, thanks!
