### ISSUE TITLE
Sample freezing on IE9 refresh

### ISSUE THREAD

**Issue by billbris** [timeglider/jquery_widget#23]
I'm attempting to get a sample timeline working using ASP.NET 4 with MVC 3.

I have succeeded getting a timeline (the sample idaho.json timeline) to display properly in both Firefox and IE9.  However, when I refresh the IE9 page, the timeline freezes with the "loading" message displayed in the timeline box.  This behavior does not occur on Firefox v6.

1) Are there hints as to what I may be doing incorrectly.
2) If not, what can I provide to help get rid of this problem?

I am using the Timeglider code downloaded from github in the file: timeglider-jquery_widget-345442f.zip

A bit more information:
I am working on this sample using MS Visual Studio 2010.  
1. After a reboot, loading the project, and starting the debugger the idaho.json sample loads and displays just fine.
2. Refreshing the page causes the page to freeze as noted above (the browser is not frozen, only the "loading" issue).
3. After killing the debugger, and then restarting, the sample does not load (same bad behavior).
4. After killing the development web server (automatically started by the dev environment), and then restarting the debugger, the sample loads just fine, and then refreshing, etc. continues with the bad behavior.
5. Also, with the sample loaded and displayed correctly, I opened another browser window using the localhost server address, and the sample does not load/display in IE9.
6. During all of this, the Firefox 6 browser continues to work as expected.

This tells me that there is something browser specific going on.  I hope this extra info helps.

**Comment by timeglider** [comment]
Sorry I've not been more up to speed with Github issues: Is this still happening for you? I've tested myself on IE9 and don't see this issue (though now I see other issues ; )
