### ISSUE TITLE
Timeglider is not working.... stuck on loading

### ISSUE THREAD

**Issue by jameshorn165** [timeglider/jquery_widget#24]
Please help me I am developing my json file from PHP and MySQL. It was working firt day when i generate but after inserting lots of timeline into my large.json file. when i run large.html. It stucks on loading. Please help me.

**Comment by timeglider** [comment]
Hi James

Send me the JSON file and I'll see what's up. First thing I'd do is use JSON
Lint (http://jsonlint.com) and see if it's valid json there.

Michael

**Comment by jameshorn165** [comment]
please get the json file from 

http://www.myheapfo.com/large.zip

Thanks

**Comment by jameshorn165** [comment]
please get the json file from 

http://www.myheapfo.com/large.zip

Thanks

**Comment by jameshorn165** [comment]
Thanks Michael your link was very helpful. I had some bad symbols in my description field. I remove extra double quote and Timeglider running again.

Thanks

**Comment by jameshorn165** [comment]
Thanks Michael your link was very helpful. I had some bad symbols in my description field. I remove extra double quote and Timeglider running again.

Thanks

**Comment by gjt2889** [comment]
Another thing that causes this behavior of getting stuck on 'Loading' is forgetting to add the MIME Type for JSON in IIS.  

ext: .json  
MIME type: application/json

**Comment by krmmalik** [comment]
I'm also having the same issue. I used .net to construct the json data, but im loading that json data into a variable and passing it to the timeline. It gets stuck on "loading" - Was working somewhat previously but i updated the timeline files this morning with latest code.

I checked my json in jslint and it comes back with no errors.

Console window in chrome shows "Uncaught TypeError: undefined is not a function" for Backbone-min.js on line 18

**Comment by timeglider** [comment]
eemouk:  Can you send your JSON file? I'm not able to reproduce this issue,
so there might be some data point that I'm missing.

Michael

**Comment by jameshorn165** [comment]
Hi,
I have resolved this issue by myself taking too much time. You have to check Json file. YOu must have some entries that break json format.

I had problem in my description.

because when i submit description like this  [ This is the very new place "Jordan" ] in this case. It submit fairly into mysql but when i parse it with json. Json array breaks. like that
event:{[
"id" : '1',
"description:"This is the very new place "Jordan"",    -------------- here event array breaks and all json file format goes wrong. 

so you have to replace double quotes and single quotes from your description field. I hope after doing this you will never face any error.

Thanks,
James.H

**Comment by jameshorn165** [comment]
repalce double quotes and single quotes into HTML formatted text

http://www.ascii.cl/htmlcodes.htm

**Comment by jameshorn165** [comment]
Ok send me your json file. I will point you out where is the error.

**Comment by jameshorn165** [comment]
[
{
    "id": "idahoTimeline",
    "title": "A Really Long, But "Incomplete" History of Idaho",
    "focus_date": "1863-07-01 12:00",
    "initial_zoom": "47",
    "events":
    [

  {
        "id": "1391bce",
        "title": "TEST BCE EVENT",
        "startdate": "-1000-07-01 12:00",

```
    "description": "TEST BCE EVENT.",
    "icon": "triangle_green.png",
    "low_threshold": "1",
    "high_threshold": "100",
    "importance": "80"
},


{
    "id": "1391",
    "title": "Smallpox Strikes the Shoshone",
    "startdate": "1740-07-01 12:00",
    "enddate": "1800-07-01 12:00",

    "description": "Shoshone bands obtain horses for transportation but are decimated by smallpox spread from European sources.",
    "icon": "triangle_green.png",
    "low_threshold": "1",
    "high_threshold": "60",
    "importance": "50",
    "ypix": "0",
    "slug":""
}
]
```

}
]

This json file has error. See on first array title. It has double quotes that break entire json. I hope you must understood now. 

Enjoy

**Comment by krmmalik** [comment]
Thanks for replying so soon.
Here's the link to my json file:

http://dl.dropbox.com/u/3417415/timeglider/json_tests/tgsample.json

**Comment by timeglider** [comment]
I'm able to load this into a timeline successfully;
Can you tell me the OS and browser you're using?
(We're having some issues right now with < IE 7)

**Comment by krmmalik** [comment]
I tried Chrome and Firefox, but i found the issue.
Basically because of the way that im constructing the json and the way the page is being loaded, the json isnt fully ready always when the page is loaded.

So i've added a function that waits for the page to fully load and then constructs the object and then the timeline, and now it works beautifully.

I'm ever so sorry to have wasted your time. I really appreciate the speedy responses and the genuine help, at least it gave me a lead and i was able to look in the right direction.

Really awesome project you have going in here. Thank you once again.

**Comment by timeglider** [comment]
No problem  glad you figured it out.

Michael

**Comment by jameshorn165** [comment]
Awesome man you found and fixed :)

**Comment by ApayRus** [comment]
i downloaded files from this link https://github.com/timeglider/jquery_widget/downloads
and wanna see demo files
but work only file table.html 
others "stuck on loading"
i think problem with json.... or it work only online?

_upd_
on my netbook OS Windows XP. But on laptop my wife OS is Windows 7 , and all demos is working nice
