### ISSUE TITLE
Multiple timelines loaded on one page

### ISSUE THREAD

**Issue by joanna1902** [timeglider/jquery_widget#25]
We have a following scenario: a user starts a search, and the search results are a list of people, each of them have a profile. We want to present each profile with a Timeline, and on one html page we want to present profiles of 3 persons. This means on one html page, there will be three timelines loaded. We have tried the timeglider jquery_widget. We have gotten three timeline containers, but no events are presented. It seems that only the profile of the last person's is loaded. How can we customize the timeglider widget, in order to present multiple timelines on one page?

Thanks in advance.

joanna1902

**Comment by timeglider** [comment]
Sorry I've not been more on top of these issues.  You can load multiple timelines into one instance of the jQuery widget: the JSON data is an array of timeline objects. See this example of JSON: http://timeglider.com/jquery/json_tests/mylife.json, which is in an active timeline here: http://timeglider.com/jquery/mylife.html.
