### ISSUE TITLE
Link always appears in popup dialog

### ISSUE THREAD

**Issue by FattusMannus** [timeglider/jquery_widget#3]
Passing in an empty or not specifying a link parameter still results in a link being shown in the popup

**Comment by timeglider** [comment]
This has been taking care of: If there's no link in the event JSON, no link shows. I also improved the import structure: You can use an array of objects like this:
[{"label":"Wikipedia", "url":"http://en.wikipedia.org/wiki/Javascript"}, {"label":"NYTimes", "url":"http://nytimes.com"}]  to import multiple links into the same event, shown across the bottom of the modal.
Only file that changed: js/timeglider/TG_TimelineView.js
