### ISSUE TITLE
Infinite loading in google chrome

### ISSUE THREAD

**Issue by PauloFerreira** [timeglider/jquery_widget#31]
Hello,
When i try to open the timelines in the browser Google Chrome, it stays forever in the loading part. Does somebody have a solution for this?

**Comment by timeglider** [comment]
Are you loading from a live web page, or trying
to load the widget locally?

On Mon, Jan 16, 2012 at 7:01 AM, PauloFerreira <
reply@reply.github.com

**Comment by PauloFerreira** [comment]
I downloaded the files to my computer and when i try to open a page, such as demo.html or large.html, with Google Chrome, it doesn't pass the loading screen. I'm running the pages locally yes.

I am in windows 7 and i tried with other PC and it also doesn't work in google chrome. I tried with firefox and IE and it works in those browsers. Thanks for the fast reply.

**Comment by timeglider** [comment]
Chrome and other browsers (except Firefox) block loading JSON from a local
file, treating it as an "out of domain file".

You probably would see this in the console, if you open right-click and
choose "inspect element", then click the console tab:

XMLHttpRequest cannot load
file:///YOURFILES/json_tests/js_history.jsonfile:///SITES/timeglider.com/httpdocs/jquery/json_tests/js_history.json.
Origin null is not allowed by Access-Control-Allow-Origin.

You need to run something like MAMP (http://www.mamp.info/en/index.html) or
another localized (asp/php/etc) web server to have it work properly on your
own machine.

On Mon, Jan 16, 2012 at 10:13 AM, PauloFerreira <
reply@reply.github.com

**Comment by PauloFerreira** [comment]
Oh, thanks, i didn't knew that part of visiting the console of chrome.
 I installed WAMP and it worked, but there isn't another way of correcting this without installing a server? I saw a command line: chrome.exe --allow-file-access-from-files, but it didn't work. Do you know another way?

Thanks for the help, you were a big aid.
