### ISSUE TITLE
Is it possible more than one timeline?

### ISSUE THREAD

**Issue by PauloFerreira** [timeglider/jquery_widget#32]
Hello,

Sorry for posting another comment in here, but is it possible to add more timelines to the html page? Like one or more than one timeline below the main one? I am kind of new to this and i don't understand very well the code.

**Comment by timeglider** [comment]
I'm not exactly sure what you mean by "the html page".  
Timeline data loaded from an HTML table is limited to a single timeline. But if you're loading JSON, you can load 2+ timelines in the initial JSON load: the entire JSON object is an array of timeline objects, each of which has events. Here is an example of a JSON file with two timelines in it: http://timeglider.com/jquery/json_tests/mylife.json
The timeline for this is visible here: http://timeglider.com/jquery/mylife.html
