### ISSUE TITLE
show/hide filter always visible?

### ISSUE THREAD

**Issue by deecsaunders** [timeglider/jquery_widget#33]
Is it possible to have the show/hide filter feature show by default and not in a modal window?

**Comment by timeglider** [comment]
This isn't the type of thing that we'd build into the widget per se, as an
option  but you can achieve it with something like this. The timeout may
not be necessary; it just makes sure that any other dynamically loaded
templates are in the DOM.

setTimeout(function() {
    $(".timeglider-filter-bt").trigger("click");
}, 500);

On Wed, Jan 25, 2012 at 4:37 AM, David <
reply@reply.github.com

**Comment by deecsaunders** [comment]
Thanks very much, works exactly how I need.
