### ISSUE TITLE
Pulling the Description from modal to the timeline itself (no more modal)

### ISSUE THREAD

**Issue by rhev25** [timeglider/jquery_widget#35]
Hello, I just want to ask if this is possible?... I want the description being displayed from the timeline itself, so there will be no clickable timeline item for you to see the description. What I want to do is to put the description on the top of every timeline title... and ofcourse the image thumbnail will retain on the top of the timeline.

[Image]

[Description]

[Timeline title [year 2000 - 2001]

is this possible?... I'm so noob when it comes to jquery...sorry about that...i hope you can help me with this..thanks :)

**Comment by timeglider** [comment]
There's no easy solution to this — really it looks like you'd have to dig into the Backbone view for the Timeline itself. Inside of TG_TimelineView.js do a search for this:

   tg.TG_TimelineView = Backbone.View.extend({

and you'll see there how the timeline "frame" gets created. You could add the description into that view by drawing from the description in the ("tmpl") template by adding a ${description} in there somewhere, and perhaps add a special class to an element such that you can style it from CSS.
