### ISSUE TITLE
Multiple Popups cause each other to move on closing

### ISSUE THREAD

**Issue by FattusMannus** [timeglider/jquery_widget#4]
Using chrome, when I open multiple popups (eg 3) and then close the 3rd one ive opened, the 2nd one will jump up.

**Comment by timeglider** [comment]
This seems to be the case across browsers. A real puzzle, as the only thing happening is the $ fadeout and removal of a "sibling" modal... Working on it.

**Comment by timeglider** [comment]
Okay, pretty simple: we needed to have the position set to absolute for modals in the CSS.
