### ISSUE TITLE
The Trouble with Internet Explorer

### ISSUE THREAD

**Issue by chieffff** [timeglider/jquery_widget#48]
This widget  works very slowly  in Internet Explorer 7.0...

**Comment by timeglider** [comment]
Hey there chieffff.  IE7 is not a high priority for us. If you are able to do some performance testing with it, though, I welcome that!

**Comment by chieffff** [comment]
Unfortunately, IE is still popular in Russia. I am ready to do some testing, but I need some instructions :)
