### ISSUE TITLE
Hide Events for All Timelines on Load

### ISSUE THREAD

**Issue by ineedfat** [timeglider/jquery_widget#54]
Hi, 

I have multiple timelines, and I would like to hide/collapse all events at load time. 

I tried $('.expand-collapse').trigger('click'); but only the first item get triggered. 

Please tell me if there's a better way to do this.

Thanks,

**Comment by timeglider** [comment]
Yes, you can do this by adding a "display" property on the timeline object in the JSON.  The value of it can either be "expanded" or "collapsed".  We'll be adding the ability to show the timeline "above" the title bar element or "below", so this likely will grow to "expanded-above" and "expanded-below" (defaulting to above if it's just "expanded")

**Comment by ineedfat** [comment]
Thank you for the fast response. 

I was not able to get the timelines to collapse all events at load. Below is the code I used to dynamically generate each timeline object. 

FYI, I'm using timeglider-0.1.4.min.js

``` javascript
var newTimeline= {
                        'id': key,
                        'display': 'collapsed',
                        'title': values[0].FullName,
                        'description': 'Activities within last 24 hours.',
                        'timezone': '-07:00',
                        'initial_zoom': 2,
                        'top': topPosition + 'px',
                        'events': eventJson
                    };
```
