### ISSUE TITLE
Vertical scrolling/dragging to see events off the screen

### ISSUE THREAD

**Issue by gabaum10** [timeglider/jquery_widget#55]
So this might be just how I am structuring my data, but if there are a lot of events on a single time interval, they can get pushed off the screen.  There is literally no way to see them once they are off.  I was looking through the plugin code, and it looks like there is an option: 

event_overflow:"plus"  // plus | scroll 

Unfortunately, when I set it to scroll, all my events stack up on top of each other (like in the same Y-index), instead of seeing the desired effect.  I am not quite sure exactly what is going on there.  I am going to keep looking to see if I can find out what's going on, but any help would be greatly appreciated...

**Comment by timeglider** [comment]
Let me do some tinkering with this and see
what the problem is. This might be a regression
issue related to the value of the "ceiling" that's
set (which determines where to place the icons
in the "plus" mode)

---- Michael

On Fri, Sep 7, 2012 at 9:56 AM, gabaum10 notifications@github.com wrote:

> So this might be just how I am structuring my data, but if there are a lot
> of events on a single time interval, they can get pushed off the screen.
> There is literally no way to see them once they are off. I was looking
> through the plugin code, and it looks like there is an option:
> 
> event_overflow:"plus" // plus | scroll
> 
> Unfortunately, when I set it to scroll, all my events stack up on top of
> each other (like in the same Y-index), instead of seeing the desired
> effect. I am not quite sure exactly what is going on there. I am going to
> keep looking to see if I can find out what's going on, but any help would
> be greatly appreciated...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/timeglider/jquery_widget/issues/55.

## 

---

founder / lead developer
_Timeglider_
http://timeglider.com
michael@timeglider.com
twitter @timeglider
208.850.8512

---

**Comment by gabaum10** [comment]
Yeah, I noticed that.  When I was stepping through, I saw that it gets set to 0 if if you set event_overflow to scroll. (Line 2178 in TG_TimelineView.js)  There is a TODO comment that made me wonder if that was a feature that was not completed yet.

I guess I am also curious how that will be handled.  I assume it would just be a scroll/drag in the Y direction as well as the X?

**Comment by timeglider** [comment]
This is definitely a feature in development: there
can't be a natural browser scrollbar, but rather
a hand-made scroller, as we don't want to throw
the entire UI into a scrolling action.

If there's major event overflow, you should also
consider different filtering strategies, using
thresholds to eliminate certain groups of data
at wider scopes, etc, combining that with
importance values.  But, yes, sometimes, you
just gotta scroll...

On Fri, Sep 7, 2012 at 11:08 AM, Geoff notifications@github.com wrote:

> Yeah, I noticed that. When I was stepping through, I saw that it gets set
> to 0 if if you set event_overflow to scroll. (Line 2178 in
> TG_TimelineView.js) There is a TODO comment that made me wonder if that was
> a feature that was not completed yet.
> 
> I guess I am also curious how that will be handled. I assume it would just
> be a scroll/drag in the Y direction as well as the X?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/timeglider/jquery_widget/issues/55#issuecomment-8371776.

## 

---

founder / lead developer
_Timeglider_
http://timeglider.com
michael@timeglider.com
twitter @timeglider
208.850.8512

---

**Comment by gabaum10** [comment]
Yeah, I am going to look into doing some better filtering by importance.  But you're right, sometimes there is no avoiding the scroll/overflow.  Do you know what would be causing the weird behavior where the events are placed directly on top of each other (as in a row in the Z-direction, not stacked in the Y-direction)?

**Comment by santoshtripathi** [comment]
Is the issue resolved?? Do we have any work around for this? I am facing the same problem.

**Comment by gabaum10** [comment]
I haven't heard anything more about this, and since there hasn't been a
release, I'd say it's still an issue.

**Comment by santoshtripathi** [comment]
Ok.. Do you have any work around for this problem??

**Comment by gabaum10** [comment]
No, I just modified my solution to work differently.  I didn't want to hack things too badly.

**Comment by timeglider** [comment]
I was able to fix this by raising the "ceiling" value in TG_TimelineView.js on ~ line 2793 to an extremely high number, giving it a virtually unlimited ceiling, and thus preventing the "compressing" of icons at the top of the frame.

There is no "scrollbar" that will appear once events stack above the frame. I'm not sure what the best course of action is, but you can create some UI elements with jQuery like this to raise and lower the group of events, having created two buttons with "scrolldown" and "scrollup" ids:

``` javascript

$("#scrolldown").bind("click", function() {
    $(".timeglider-timeline-envelope").animate({top:"+=100"})
})

$("#scrollup").bind("click", function() {
    $(".timeglider-timeline-envelope").animate({top:"-=100"})
})

```

I've put scrollup/down buttons in the "methods.html" page even though the event_overflow
is set to "plus".  I think I'll likely change the options on this to "ceiling" and "no_ceiling" or
something like that.
