### ISSUE TITLE
Adding multiple timelines places them directly on top of each other (Z-direction)

### ISSUE THREAD

**Issue by gabaum10** [timeglider/jquery_widget#56]
If I try and add several timelines to a single view, they are all placed on top of each other when you add them in through the menu in the bottom right.  I would expect them to stack up in the Y-direction.  Could this be related in some part to issue #55?  There may be a configuration option I am missing...

To replicate, simply use a dataset with multiple timelines.  When you show them, you will see exactly what I am talking about.

**Comment by timeglider** [comment]
On the level of the timeline data, you can now add a "bottom" value so that when it loads, it's positioned at the specified "height" (distance upward from the bottom).
