### ISSUE TITLE
Zoom one axis only

### ISSUE THREAD

**Issue by nrv** [timeglider/jquery_widget#57]
Hi,

when zooming, the font size of events is also changed. Is there a way to avoid this and have only the time zoomed ? This would allow to better display portions of time where a huge amount of events are stacked.

Nicolas

**Comment by timeglider** [comment]
There's an option for the widget called "size_importance"; set to false, the font size will not change, and will only be set to the widget's "base_font_size" property.  The reason we created the size-importance feature, though, is actually to allow for better rendering of large sets of data — but it means that you need to apply relevant/accurate "importance" values for events, too.  font-size = (importance/zoom_level) \* base_font_size.
