### ISSUE TITLE
Images and json problem

### ISSUE THREAD

**Issue by talamaska** [timeglider/jquery_widget#7]
first, i'm trying the functionality with html table, the date is working ok.
I put a th class="tg-image_url"
to put an image in the fancy-box, not in the timeglider, but it seems not working, if i put the param th class="tg-image" it is showing the image in timeglider and in the fancybox
i tried also to work with json, but it keeps saying json not valid validate with jsonLint, and i did, and it was valid, first tough it's the escaping of the php json_encode function, tryied to strip slashes, but it's the same result - invalid json. please take a look.
here is the json that i generate with php
http://jsfiddle.net/goldy/6EcJq/

by looking in TG_timelineview, i feel very confused, that you're taking the image not image_url to display it in fancybox.
actually i didn't find anywhere where you're using image_url and it is used in examples. i don't want to have an image on the timeline glider only in fancybox.

**Comment by talamaska** [comment]
OK I think i have fixed the json problem, strange for me.
in php i'm starting like this 
$data = array(  "id"=> "jshist",
                                "title"=> "Humanline",
                                "focus_date"=> "0001-01-01 12:00:00",
                                "initial_zoom"=> "80",
                                "events" => "");
for($i = 0; $i < $items_num ; $i++){
$temp = array( event data );
$data["events"][] = $temp;
}
echo json_encode($data);

but it was not valid even if I can debug log and see the objects, instead
after looking at your json test i saw that the json object is wraped in [], so i do
json_encode(array($data));
which return the json in the awaited format i thing it's a problem of getJSON.
the problem with a missing image in event description still persist, when i put image_url = "/images/test.png"

and for what are 
"low_threshold": "1",
"high_threshold": "100",
"ypix": "0"

**Comment by timeglider** [comment]
Hi there

I'll try to address your issues in the next couple
days.  Thanks for your patience!

The image parameter needs to be "image" rather
than "image_url" ---- I'll add this (with its options)
into the JSON docs.

Michael

**Comment by talamaska** [comment]
so if you have removed image_url from options, you should make different way to control the image in the timeglider. as i said before i don't want it, i just used your examples, can you update them too, when you remove some options from the code?
