### ISSUE TITLE
Bands implementation

### ISSUE THREAD

**Issue by jmaynier** [timeglider/jquery_widget#8]
Hi,

Can I separate my events in different tracks and bands like I can do in the SIMILE timeline widget ?

Cheers,

Jean

**Comment by timeglider** [comment]
We don't have that capability yet; but using a combination of the legend and well-defined icons, you can achieve similar results, at least in terms of getting as sense of how the data separates out.  If you can envision the ideal UI for this type of thing ------- and how it will handle event-stacking beyond the ceiling of a particular topical "lane" -------- I'd love to see an image.  I imagine doing something that eliminates vertical differentiation for each topic, and simply overlaps things until you zoom far enough out.

**Comment by jmaynier** [comment]
For example with simile we used different bandInfos to groups events together horizontally :
http://www.imagup.com/data/1122134038.html

It works because we don't have to many close events on the same lane. But if the user zoom out a lot, some events are not shown because there is not enough vertical space to display them. You could either groups events when there are too close horizontally and there is not enough space or just disable the zoom out too far.

Let me know what do you think ?

**Comment by timeglider** [comment]
Right now the  best way to achieve something like this is to set absolute heights of events: in the event JSON, you can use the "y_position", setting it to a distance upward from the time-ruler.  So, for example, if you wanted all of a certain type (or topic) of event in a "band" you could set the y_position of all of them to be at 50.

We're not planning to do any kind of "swimlanes" or bands like this in the near term. It adds too many levels of complexity for most users, and creates something that doesn't actually look or behave very good.
